# Generated by Django 4.0.4 on 2022-04-28 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0007_stock_likecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
                ('strategy', models.CharField(choices=[('매수', '매수'), ('중립', '중립'), ('매도', '매도')], default='중립', max_length=3)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('likeCount', models.PositiveIntegerField(default=0)),
                ('commentCount', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postAuthor', to=settings.AUTH_USER_MODEL)),
                ('likeUsers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postLikeUsers', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postStock', to='stock.stock')),
            ],
        ),
    ]
