# Generated by Django 4.0.4 on 2022-04-29 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likeUsers',
        ),
        migrations.AddField(
            model_name='post',
            name='likeUsers',
            field=models.ManyToManyField(related_name='postLikeUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
