# Generated by Django 4.0.4 on 2022-04-17 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 17, 16, 54, 575253)),
        ),
    ]
