# Generated by Django 4.0.4 on 2022-04-19 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
