# Generated by Django 4.0.4 on 2022-04-20 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockCode', models.CharField(max_length=6)),
                ('stockName', models.CharField(max_length=100)),
                ('ipoDate', models.CharField(max_length=11)),
                ('kospi', models.CharField(max_length=6)),
                ('perValue', models.PositiveIntegerField(default=0)),
                ('stockNum', models.PositiveBigIntegerField()),
                ('likeUsers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockLikeUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
