# Generated by Django 4.0.4 on 2022-04-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_likeusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='perValue',
            field=models.CharField(max_length=11),
        ),
    ]
