# Generated by Django 4.0.4 on 2022-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_likeusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ipoDate',
            field=models.DateField(),
        ),
    ]
