# Generated by Django 4.0.4 on 2022-04-23 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0005_alter_stock_ipodate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='likeUsers',
        ),
        migrations.AddField(
            model_name='stock',
            name='likeUsers',
            field=models.ManyToManyField(related_name='stockLikeUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
