# Generated by Django 4.0.4 on 2022-04-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stock_likeusers_stock_likeusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='likeCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
