# Generated by Django 4.0.4 on 2022-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockCode', models.CharField(max_length=6)),
                ('stockName', models.CharField(max_length=55)),
                ('ipoDate', models.CharField(max_length=11)),
                ('kospi', models.CharField(max_length=6)),
                ('perValue', models.PositiveIntegerField(default=0)),
                ('stockNum', models.PositiveBigIntegerField()),
            ],
        ),
    ]
