# Generated by Django 4.0.4 on 2022-04-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockCode', models.CharField(max_length=30)),
                ('stockName', models.CharField(max_length=30)),
                ('value', models.PositiveIntegerField()),
                ('totalAssets', models.DecimalField(decimal_places=2, max_digits=9)),
                ('per', models.DecimalField(decimal_places=2, max_digits=6)),
                ('roa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('take', models.PositiveIntegerField()),
                ('takeRatio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('perValue', models.PositiveIntegerField()),
                ('operatingProfit', models.PositiveIntegerField()),
                ('ipoDate', models.DateField()),
            ],
        ),
    ]
