# Generated by Django 4.0.4 on 2022-04-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stock_stockname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
