# Generated by Django 4.0.4 on 2022-04-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_likeusers_comment_likeusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likeCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
