# Generated by Django 4.0.4 on 2022-04-20 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likeUser',
        ),
        migrations.AddField(
            model_name='comment',
            name='likeUsers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentLikeUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
