# Generated by Django 4.0.4 on 2022-04-18 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockComment', '0003_alter_comment_content_alter_comment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 23, 55, 978191)),
        ),
    ]
