# Generated by Django 4.0.4 on 2022-05-10 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0005_recomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('likeCount', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reCommentAuthor', to=settings.AUTH_USER_MODEL)),
                ('likeUsers', models.ManyToManyField(related_name='reCommentLikeUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ReComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='reComment',
            field=models.ManyToManyField(related_name='commentReComment', to='comment.commentbase'),
        ),
    ]
